### ISSUE TITLE
Link to Youtube presentation

### ISSUE THREAD

**Issue by viccooper142** [aws-samples/aws-appsync-chat-starter-react#2]
This code was part of a presentation given at AWS re:Invent 2018. It took me a bit to track it down so I thought I would share the link with others https://www.youtube.com/watch?v=0H5F0PI2-SU
Great job Brice and Ed and thanks for sharing the code!

**Comment by awsed** [comment]
Thank you very much for the reminder, @viccooper142, and thank you for the kind words. Just added the link to the README file
