### ISSUE TITLE
Step 11 error

### ISSUE THREAD

**Issue by viccooper142** [aws-samples/aws-appsync-chat-starter-react#3]
I'm having a problem when I try to run 
`sam package --template-file ./backend/deploy.yaml --s3-bucket $DEPLOYMENT_BUCKET_NAME --output-template-file packaged.yaml`
I get the following errors
`Unable to upload artifact . referenced by CodeUri parameter of ChuckBot resource.
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied`

I'm using 
aws-cli/1.16.77 
Python/2.7.10 
Darwin/18.2.0 
botocore/1.12.67

Thanks!

**Comment by awsed** [comment]
It looks like an issue with the S3 bucket. Can you confirm you have access to the bucket from the CLI?

You can also try to manually replace `$DEPLOYMENT_BUCKET_NAME` with the actual bucket name and check if there's still a problem

**Comment by viccooper142** [comment]
Thank, I got it working by running `aws configure` again and double checking my credentials
