### ISSUE TITLE
not working aws-appsync-chat-starter-react sample

### ISSUE THREAD

**Issue by psyrenpark** [aws-samples/aws-appsync-chat-starter-react#7]
open http://localhost:3000/

Argument of query SearchUsers(
  $filter: SearchableUserFilterInput
  $sort: SearchableUserSortInput
  $limit: Int
  $nextToken: Int
) {
  searchUsers(
    filter: $filter
    sort: $sort
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      username
      registered
      userConversations {
        items {
          id
          name
          status
          convoLinkUserId
        }
        nextToken
      }
    }
    nextToken
  }
}
 passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document

invariant
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/node_modules/invariant/browser.js:34
parser
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/node_modules/react-apollo/react-apollo.browser.umd.js:334
graphql
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/node_modules/react-apollo/react-apollo.browser.umd.js:1717
▲ 3 stack frames were expanded.
Module../src/components/SearchResultList.js
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/src/components/SearchResultList.js:219
  216 |   return filter
  217 | }
  218 | 
> 219 | const SearchResultListWithData = compose(
  220 |   graphql(searchUsers, {
  221 |     name: 'userSearchData',
  222 |     skip: props => !props.term,
View compiled
__webpack_require__
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/components/SideBar.js
http://localhost:3000/static/js/main.chunk.js:5618:76
__webpack_require__
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/components/chatapp.js
http://localhost:3000/static/js/main.chunk.js:6016:67
__webpack_require__
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/App.js
http://localhost:3000/static/js/main.chunk.js:128:78
__webpack_require__
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:7094:62
__webpack_require__
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
fn
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
0
http://localhost:3000/static/js/main.chunk.js:7203:18
__webpack_require__
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:782
  779 | };
  780 | 
  781 | // Execute the module function
> 782 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  783 | 
  784 | // Flag the module as loaded
  785 | module.l = true;
View compiled
checkDeferredModules
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | return result;
View compiled
Array.webpackJsonpCallback [as push]
C:/Users/test/work/dev-Phantomjs/DEV_APPSYNC_CHAT/aws-appsync-chat-starter-react/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:57

similar problem :
https://github.com/apollographql/graphql-tag/issues/185

**Comment by rush86999** [comment]
I have the same problem; All that was done was the instructions were followed exactly with current react stack.  This app never started. 

here is the package.json
```
{
  "name": "chatql-react-app-reinvent",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "aws-amplify": "1.1.9",
    "aws-amplify-react": "2.0.5",
    "aws-appsync": "1.3.4",
    "aws-appsync-react": "1.1.4",
    "bootstrap": "^4.2.1",
    "downshift": "^2.2.3",
    "graphql-tag": "^2.10.1",
    "lodash.clonedeep": "^4.5.0",
    "lodash.debounce": "^4.0.8",
    "lodash.get": "^4.4.2",
    "moment": "^2.24.0",
    "node-sass-chokidar": "^1.3.3",
    "react": "^16.7.0",
    "react-apollo": "2.2.4",
    "react-click-n-hold": "^1.0.7",
    "react-custom-scrollbars": "^4.2.1",
    "react-d3-cloud": "^0.6.0",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.1",
    "react-sizeme": "^2.5.2",
    "react-sound": "^1.2.0",
    "react-speech-recognition": "^1.0.7",
    "react-spinners": "^0.4.8",
    "react-tiny-popover": "^3.4.2",
    "reactstrap": "^6.4.0",
    "rxjs": "^6.3.3",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "9",
    "babel-runtime": "^6.26.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-import": "^2.16.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-standard": "^3.1.0",
    "npm-run-all": "^4.1.5",
    "prettier-eslint": "^8.8.2",
    "standard": "^11.0.1"
  },
  "scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "build-js": "react-scripts build",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```
here's the error
```
Uncaught Error: Argument of query SearchUsers(
  $filter: SearchableUserFilterInput
  $sort: SearchableUserSortInput
  $limit: Int
  $nextToken: Int
) {
  searchUsers(
    filter: $filter
    sort: $sort
    limit: $limit
    nextToken: $nextToken
  ) {
    items {
      id
      username
      registered
      userConversations {
        nextToken
      }
    }
    nextToken
  }
}
 passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document
    at invariant (browser.js:34)
    at parser (react-apollo.browser.umd.js:334)
    at graphql (react-apollo.browser.umd.js:1717)
    at Module../src/components/SearchResultList.js (SearchResultList.js:219)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Module../src/components/SideBar.js (SearchResultList.js:243)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Module../src/components/chatapp.js (UserBar.js:34)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Module../src/App.js (App.css?da7c:45)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Module../src/index.js (index.css?02e3:45)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Object.0 (registerServiceWorker.js:117)
    at __webpack_require__ (bootstrap:782)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

**Comment by awsed** [comment]
Your package.json is different from https://github.com/aws-samples/aws-appsync-chat-starter-react/blob/master/package.json . Suggest to delete the "node_modules" folder, use the original package.json version from the repo and try again.

**Comment by rush86999** [comment]
Nope sorry still didn't work.

**Comment by awsed** [comment]
I just cloned the repo in a temporary folder, executed the instructions and deployed from scratch, created 2 users, logged in with both so they are registered in DDB and with the last logged in user searched for the previous one:

```MessagePane - componentDidMount
MessagePane.js:115 {width: 1110.015625, height: 747, position: null}
chatapp.js:38 run register - before true undefined
chatapp.js:38 run register - before true undefined
chatapp.js:38 run register - before false null
chatapp.js:40 run register 432f15ac-3db9-43fd-a228-dd26eca1e01c false
chatapp.js:315 prev getUser {getUser: null}
chatapp.js:38 run register - before false {id: "432f15ac-3db9-43fd-a228-dd26eca1e01c", username: "Standby", registered: false, userConversations: {…}, __typename: "User"}
chatapp.js:315 prev getUser {getUser: null}
chatapp.js:315 prev getUser {getUser: null}
chatapp.js:38 run register - before false {id: "432f15ac-3db9-43fd-a228-dd26eca1e01c", username: "jdoe", registered: true, userConversations: {…}, __typename: "User"}
chatapp.js:46 initConvo {id: "99d3485b-1b4e-40cd-b8dc-fa004a43ceb2", username: "ed", registered: true, userConversations: {…}, __typename: "User"}
chatapp.js:62 no convo, launch new
chatapp.js:124 update,  {id: "-1", name: "direct", createdAt: "", __typename: "Conversation", associated: {…}}
chatapp.js:124 update,  {id: "-1", name: "direct", createdAt: "", __typename: "Conversation", associated: {…}}
chatapp.js:124 update,  {id: "99d3e52d-a03c-4ec0-83eb-69e90fffab9d", name: "direct", createdAt: "2019-01-30T03:55:27.782Z", associated: {…}, __typename: "Conversation"}
chatapp.js:149 linkNewConversation - start 99d3e52d-a03c-4ec0-83eb-69e90fffab9d 99d3485b-1b4e-40cd-b8dc-fa004a43ceb2 jdoe (chat)
chatapp.js:149 linkNewConversation - start 99d3e52d-a03c-4ec0-83eb-69e90fffab9d 432f15ac-3db9-43fd-a228-dd26eca1e01c ed (chat)
chatapp.js:136 next steps (2) [{…}, {…}]
chatapp.js:186 updateToReadyConversation - update {id: "7a18819a-4e4a-48bc-a9f7-4957353d650b", name: "jdoe (chat)", status: "CREATING", conversation: {…}, __typename: "ConvoLink"}
chatapp.js:215 confirmLink ,  {__typename: "ConvoLink", id: "7a18819a-4e4a-48bc-a9f7-4957353d650b", name: "jdoe (chat)", convoLinkUserId: "-1", status: "CONFIRMING", …}
chatapp.js:186 updateToReadyConversation - update {id: "670428ea-39f4-46fd-92fb-a9ad9e77d193", name: "ed (chat)", status: "CREATING", conversation: {…}, __typename: "ConvoLink"}
chatapp.js:215 confirmLink ,  {__typename: "ConvoLink", id: "670428ea-39f4-46fd-92fb-a9ad9e77d193", name: "ed (chat)", convoLinkUserId: "-1", status: "CONFIRMING", …}
chatapp.js:215 confirmLink ,  {__typename: "ConvoLink", id: "7a18819a-4e4a-48bc-a9f7-4957353d650b", name: "jdoe (chat)", convoLinkUserId: "-1", status: "CONFIRMING", …}
chatapp.js:215 confirmLink ,  {__typename: "ConvoLink", id: "670428ea-39f4-46fd-92fb-a9ad9e77d193", name: "ed (chat)", convoLinkUserId: "-1", status: "CONFIRMING", …}
chatapp.js:215 confirmLink ,  {__typename: "ConvoLink", id: "670428ea-39f4-46fd-92fb-a9ad9e77d193", name: "ed (chat)", convoLinkUserId: "-1", status: "CONFIRMING", …}
chatapp.js:215 confirmLink ,  {id: "7a18819a-4e4a-48bc-a9f7-4957353d650b", name: "jdoe (chat)", convoLinkUserId: "99d3485b-1b4e-40cd-b8dc-fa004a43ceb2", status: "READY", conversation: {…}, …}
chatapp.js:215 confirmLink ,  {__typename: "ConvoLink", id: "670428ea-39f4-46fd-92fb-a9ad9e77d193", name: "ed (chat)", convoLinkUserId: "-1", status: "CONFIRMING", …}
chatapp.js:215 confirmLink ,  {id: "670428ea-39f4-46fd-92fb-a9ad9e77d193", name: "ed (chat)", convoLinkUserId: "432f15ac-3db9-43fd-a228-dd26eca1e01c", status: "READY", conversation: {…}, …}
chatapp.js:65 Got the convo {conversation: {…}, conversationName: "ed (chat)"}
MessagePane.js:92 MessagePane - componentDidUpdate - subscribe
chatapp.js:38 run register - before false {id: "432f15ac-3db9-43fd-a228-dd26eca1e01c", username: "jdoe", registered: true, userConversations: {…}, __typename: "User"}
InputBar.js:132 submit
InputBar.js:143 file for s3 null
MessagePane.js:176 updateQuery on message subscription {getConvo: {…}} {id: "319f8c73-3b7f-4716-9ed2-faacc6bc7330", content: "Hello", createdAt: "2019-01-30T03:55:35.762Z", owner: "432f15ac-3db9-43fd-a228-dd26eca1e01c", chatbot: false, …}
MessagePane.js:190 skipping own message
```

As you can see, I cannot replicate the error.

**Comment by rush86999** [comment]
I did run an npm audit fix because the console gave a high security warning. could that be an issue? I did follow your instructions on copy pasting the package.json file and deleting the node_modules folder. Just thinking out loud. How about the issue above with the graphql-tag library above. something with doing default export a single function in a js file vs using just export for graphql operations that are generated by amplify?

**Comment by awsed** [comment]
I didn't run "npm audit fix", it is possible a new version of a specific module is causing the error. We haven't tested yet with newer versions since the last commit.

**Comment by rush86999** [comment]
So I wanted to update a possible I was going towards but didn't work out completely. The steps I took. 

1. I copied the package.json
2. deleted the node_modules folder 
3. did it both ways with npm audit fix and without to see if it made the difference. It did not.
4. used the gql library and tagged all the graphql functions generated by amplify with gql` ...`
5. this is started the app
6. created two users
7. now everything seemed to work until starting a conversation
8. conversations were being created but no convolinks or messages

here's the error
```
initConvo Objectid: "c3a261c5-9c88-4cb8-9301-83fa661c63bb"registered: trueuserConversations: {nextToken: null, __typename: "ModelConvoLinkConnection"}username: "rush"__typename: "User"__proto__: Object
12:59:43.954 main.chunk.js:6118 no convo, launch new
12:59:43.959 0.chunk.js:31012 Missing field messages in {
  "id": "-1",
  "name": "direct",
  "createdAt": "",
  "__typename": "Conversation",
  "associated
(anonymous) @ 0.chunk.js:31012
12:59:43.959 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012
12:59:43.960 main.chunk.js:6222 update,  Objectassociated: {__typename: "ModelConvoLinkConnection", items: Array(0)}createdAt: ""id: "-1"name: "direct"__typename: "Conversation"__proto__: Object
12:59:43.964 0.chunk.js:31012 Missing field messages in {
  "id": "-1",
  "name": "direct",
  "createdAt": "",
  "__typename": "Conversation",
  "associated
(anonymous) @ 0.chunk.js:31012
12:59:43.964 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012
12:59:43.965 main.chunk.js:6222 update,  Objectassociated: {__typename: "ModelConvoLinkConnection", items: Array(0)}createdAt: ""id: "-1"name: "direct"__typename: "Conversation"__proto__: Object
12:59:44.325 main.chunk.js:6222 update,  Object
12:59:44.325 main.chunk.js:6275 linkNewConversation - start 0dd0a280-1c38-48f6-b71f-9ab197f7e410 c3a261c5-9c88-4cb8-9301-83fa661c63bb nishi (chat)
12:59:44.327 0.chunk.js:31012 Missing field convoLinkUserId in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "nishi (chat)",
  "con
(anonymous) @ 0.chunk.js:31012
12:59:44.327 0.chunk.js:31012 Missing field user in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "nishi (chat)",
  "con
(anonymous) @ 0.chunk.js:31012
12:59:44.327 0.chunk.js:31012 Missing field messages in {
  "__typename": "Conversation",
  "id": "0dd0a280-1c38-48f6-b71f-9ab197f7e410",
  "name": "",
  "c
(anonymous) @ 0.chunk.js:31012
12:59:44.327 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012
12:59:44.330 main.chunk.js:6275 linkNewConversation - start 0dd0a280-1c38-48f6-b71f-9ab197f7e410 e70ddac5-cae2-4aa2-88af-c0c09459af3a rush (chat)
12:59:44.331 0.chunk.js:31012 Missing field convoLinkUserId in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "rush (chat)",
  
(anonymous) @ 0.chunk.js:31012
12:59:44.331 0.chunk.js:31012 Missing field user in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "rush (chat)",
  
(anonymous) @ 0.chunk.js:31012
12:59:44.331 0.chunk.js:31012 Missing field messages in {
  "__typename": "Conversation",
  "id": "0dd0a280-1c38-48f6-b71f-9ab197f7e410",
  "name": "",
  "c
(anonymous) @ 0.chunk.js:31012
12:59:44.331 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012
12:59:44.335 0.chunk.js:31012 Missing field convoLinkUserId in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "nishi (chat)",
  "con
(anonymous) @ 0.chunk.js:31012
12:59:44.335 0.chunk.js:31012 Missing field user in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "nishi (chat)",
  "con
(anonymous) @ 0.chunk.js:31012
12:59:44.335 0.chunk.js:31012 Missing field messages in {
  "__typename": "Conversation",
  "id": "0dd0a280-1c38-48f6-b71f-9ab197f7e410",
  "name": "",
  "c
(anonymous) @ 0.chunk.js:31012
12:59:44.335 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012
12:59:44.338 0.chunk.js:31012 Missing field convoLinkUserId in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "rush (chat)",
  
(anonymous) @ 0.chunk.js:31012
12:59:44.338 0.chunk.js:31012 Missing field user in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "rush (chat)",
  
(anonymous) @ 0.chunk.js:31012
12:59:44.339 0.chunk.js:31012 Missing field messages in {
  "__typename": "Conversation",
  "id": "0dd0a280-1c38-48f6-b71f-9ab197f7e410",
  "name": "",
  "c
(anonymous) @ 0.chunk.js:31012
12:59:44.339 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012
12:59:44.341 0.chunk.js:31012 Missing field convoLinkUserId in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "rush (chat)",
  
(anonymous) @ 0.chunk.js:31012
12:59:44.341 0.chunk.js:31012 Missing field user in {
  "__typename": "ConvoLink",
  "id": "-1",
  "status": "PENDING",
  "name": "rush (chat)",
  
(anonymous) @ 0.chunk.js:31012
12:59:44.341 0.chunk.js:31012 Missing field messages in {
  "__typename": "Conversation",
  "id": "0dd0a280-1c38-48f6-b71f-9ab197f7e410",
  "name": "",
  "c
(anonymous) @ 0.chunk.js:31012
12:59:44.341 0.chunk.js:31012 Missing field nextToken in {
  "__typename": "ModelConvoLinkConnection",
  "items": []
}
(anonymous) @ 0.chunk.js:31012

```

**Comment by awsed** [comment]
Weird... Without "npm audit fix" I can confirm everything works. I could search users, create conversations and send messages without errors.

**Comment by rush86999** [comment]
okay so i compared the mutations, and they are are all different from the package. They were autogenerated by amplify. Please note, I manually added gql tags but your package had them already configured. I suspect the same for queries and subscriptions

```
// eslint-disable
// this is an auto generated file. This will be overwritten
import gql from 'graphql-tag';

export const createConvo = gql`mutation CreateConvo($input: CreateConversationInput!) {
  createConvo(input: $input) {
    id
    name
    createdAt
    messages {
      items {
        id
        content
        createdAt
        owner
        chatbot
        isSent
        messageConversationId
      }
      nextToken
    }
    associated {
      items {
        id
        name
        status
        convoLinkUserId
      }
      nextToken
    }
  }
}
`;
export const createMessage = gql`mutation CreateMessage($input: CreateMessageInput!) {
  createMessage(input: $input) {
    id
    content
    createdAt
    owner
    chatbot
    isSent
    file {
      bucket
      region
      key
    }
    messageConversationId
    conversation {
      id
      name
      createdAt
      messages {
        nextToken
      }
      associated {
        nextToken
      }
    }
  }
}
`;
export const registerUser = gql`mutation RegisterUser($input: CreateUserInput!) {
  registerUser(input: $input) {
    id
    username
    registered
    userConversations {
      items {
        id
        name
        status
        convoLinkUserId
      }
      nextToken
    }
  }
}
`;
export const createConvoLink = gql`mutation CreateConvoLink($input: CreateConvoLinkInput!) {
  createConvoLink(input: $input) {
    id
    name
    status
    convoLinkUserId
    user {
      id
      username
      registered
      userConversations {
        nextToken
      }
    }
    conversation {
      id
      name
      createdAt
      messages {
        nextToken
      }
      associated {
        nextToken
      }
    }
  }
}
`;
export const updateConvoLink = gql`mutation UpdateConvoLink($input: UpdateConvoLinkInput!) {
  updateConvoLink(input: $input) {
    id
    name
    status
    convoLinkUserId
    user {
      id
      username
      registered
      userConversations {
        nextToken
      }
    }
    conversation {
      id
      name
      createdAt
      messages {
        nextToken
      }
      associated {
        nextToken
      }
    }
  }
}
`;

```

**Comment by rush86999** [comment]
so I copied and pasted all the mutations, subscriptions and queries files and now everything works for the chat function. I haven't tested anything else. Amplify is not generating the correct mutations for some reason. I m not sure if this is related but I already had one or two similarly named tables in the region where Amplify generated the backend. Not sure if this would cause a conflict.

**Comment by awsed** [comment]
You have the option, @rush86999 . We decided to write the mutations, queries and subscriptions ourselves. Amplify does make it easier if you choose to use codegen. It's up to you.
